name: school_projects_app
description: Мобильное приложение для управления проектами школьников

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Поднимаем минимальный SDK, чтобы разрешить новые плагины

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  # firebase_storage: ^12.3.2

  # Навигация
  go_router: ^17.2.3

  # Управление состоянием
  provider: ^6.1.1

  # Работа с датами
  intl: ^0.20.2

  # Выбор файлов
  file_picker: ^11.0.2

  # Открытие файлов и ссылок
  url_launcher: ^6.3.1

  # Иконки
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true